# Generated by Django 3.2.9 on 2021-11-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211126_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='executor',
            new_name='user',
        ),
    ]
