# Generated by Django 3.2.9 on 2021-11-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_executor_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='users',
            new_name='user',
        ),
    ]
