# Generated by Django 3.2.9 on 2021-11-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_users_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='complete_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
