# Generated by Django 3.2.9 on 2021-11-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_todo_complete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
